sot_controller:
  libname: libsot-universal-robot-controller.so
  map_rc_to_sot_device:
    motor-angles: motor-angles
    joint-angles: joint-angles
    velocities: velocities
    forces: forces
    torques: torques
    control: control

  control_mode:
    shoulder_pan_joint:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    shoulder_lift_joint:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    elbow_joint:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    wrist_1_joint:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    wrist_2_joint:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    wrist_3_joint:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY

  dt: 0.01
  jitter: 0.004
